<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting=array (
  'site_name' => '点课系统',
  'site_domain' => 'http://218.95.99.209/bysj/hj',
  'site_logo' => 'images/logo.gif',
  'site_icp' => '',
  'site_terms' => '',
  'site_stats' => '',
  'site_footer' => '',
  'site_status' => '1',
  'site_close_reason' => '网站维护升级中......',
  'site_keyword' => '点课系统',
  'site_description' => '点课系统',
  'site_theme' => 'default',
  'attachment_url' => NULL,
  'attachment_dir' => 'attachments',
  'attachment_type' => '*.jpg;*.gif;*.png;*.doc',
  'attachment_maxupload' => '2097152',
  'thumbs_preferences' => '[]',
);