<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['courses']=array (
  'id' => '1',
  'name' => 'courses',
  'description' => '课程表',
  'perpage' => '10',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'fields' => 
  array (
    3 => 
    array (
      'id' => '3',
      'name' => 'courseNo',
      'description' => '课程号',
      'model' => '1',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    14 => 
    array (
      'id' => '14',
      'name' => 'courseName',
      'description' => '课程名',
      'model' => '1',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    2 => 
    array (
      'id' => '2',
      'name' => 'courseCategory',
      'description' => '课程分类',
      'model' => '1',
      'type' => 'select_from_model',
      'length' => '0',
      'values' => 'courseCategory|categoryName',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    4 => 
    array (
      'id' => '4',
      'name' => 'courseContent',
      'description' => '课程内容',
      'model' => '1',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    6 => 
    array (
      'id' => '6',
      'name' => 'thumb',
      'description' => '课程图片',
      'model' => '1',
      'type' => 'file',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '3',
    1 => '14',
    2 => '2',
    3 => '4',
    4 => '6',
  ),
  'searchable' => 
  array (
  ),
);