<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['evaluates']=array (
  'id' => '4',
  'name' => 'evaluates',
  'description' => '评价表',
  'perpage' => '10',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'fields' => 
  array (
    12 => 
    array (
      'id' => '12',
      'name' => 'evaluateNo',
      'description' => '评价号',
      'model' => '4',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    15 => 
    array (
      'id' => '15',
      'name' => 'courseNo',
      'description' => '课程号',
      'model' => '4',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    16 => 
    array (
      'id' => '16',
      'name' => 'eveluateTime',
      'description' => '评价时间',
      'model' => '4',
      'type' => 'datetime',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    13 => 
    array (
      'id' => '13',
      'name' => 'evaluateContent',
      'description' => '评价内容',
      'model' => '4',
      'type' => 'wysiwyg_basic',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    17 => 
    array (
      'id' => '17',
      'name' => 'eveluateReply',
      'description' => '评价回复',
      'model' => '4',
      'type' => 'textarea',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '12',
    1 => '15',
    2 => '16',
    3 => '13',
    4 => '17',
  ),
  'searchable' => 
  array (
  ),
);