<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['institutes']=array (
  'id' => '5',
  'name' => 'institutes',
  'description' => '院系表',
  'perpage' => '10',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'fields' => 
  array (
    42 => 
    array (
      'id' => '42',
      'name' => 'instituteNo',
      'description' => '学院编号',
      'model' => '5',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    43 => 
    array (
      'id' => '43',
      'name' => 'instituteName',
      'description' => '学院名称',
      'model' => '5',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    44 => 
    array (
      'id' => '44',
      'name' => 'introduce',
      'description' => '学院介绍',
      'model' => '5',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    45 => 
    array (
      'id' => '45',
      'name' => 'thumb',
      'description' => '学院图片',
      'model' => '5',
      'type' => 'file',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    46 => 
    array (
      'id' => '46',
      'name' => 'email',
      'description' => '学院邮箱',
      'model' => '5',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required,valid_email',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    47 => 
    array (
      'id' => '47',
      'name' => 'contactsName',
      'description' => '联系人',
      'model' => '5',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    48 => 
    array (
      'id' => '48',
      'name' => 'contactsPhone',
      'description' => '联系电话',
      'model' => '5',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '42',
    1 => '43',
    2 => '44',
    3 => '45',
    4 => '46',
    5 => '47',
    6 => '48',
  ),
  'searchable' => 
  array (
  ),
);