<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['students']=array (
  'id' => '9',
  'name' => 'students',
  'description' => '学生表',
  'perpage' => '10',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'fields' => 
  array (
    51 => 
    array (
      'id' => '51',
      'name' => 'studentNo',
      'description' => '学号',
      'model' => '9',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    52 => 
    array (
      'id' => '52',
      'name' => 'studentName',
      'description' => '学生姓名',
      'model' => '9',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    53 => 
    array (
      'id' => '53',
      'name' => 'idCard',
      'description' => '身份证号',
      'model' => '9',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    54 => 
    array (
      'id' => '54',
      'name' => 'email',
      'description' => '邮箱',
      'model' => '9',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    55 => 
    array (
      'id' => '55',
      'name' => 'address',
      'description' => '家庭地址',
      'model' => '9',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    56 => 
    array (
      'id' => '56',
      'name' => 'password',
      'description' => '密码',
      'model' => '9',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    57 => 
    array (
      'id' => '57',
      'name' => 'majoyName',
      'description' => '专业名',
      'model' => '9',
      'type' => 'select_from_model',
      'length' => '0',
      'values' => 'instituteCategory|instituteName',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '51',
    1 => '52',
    2 => '53',
    3 => '54',
    4 => '55',
    5 => '56',
    6 => '57',
  ),
  'searchable' => 
  array (
  ),
);