<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['teachers']=array (
  'id' => '6',
  'name' => 'teachers',
  'description' => '教师表',
  'perpage' => '10',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'fields' => 
  array (
    25 => 
    array (
      'id' => '25',
      'name' => 'teacherNo',
      'description' => '工号',
      'model' => '6',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    26 => 
    array (
      'id' => '26',
      'name' => 'teacherName',
      'description' => '教师姓名',
      'model' => '6',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    27 => 
    array (
      'id' => '27',
      'name' => 'gender',
      'description' => '性别',
      'model' => '6',
      'type' => 'radio_from_model',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '3',
      'editable' => '0',
    ),
    28 => 
    array (
      'id' => '28',
      'name' => 'email',
      'description' => '电子邮箱',
      'model' => '6',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required,valid_email',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    29 => 
    array (
      'id' => '29',
      'name' => 'password',
      'description' => '密码',
      'model' => '6',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    30 => 
    array (
      'id' => '30',
      'name' => 'teachName',
      'description' => '教研室名',
      'model' => '6',
      'type' => 'select_from_model',
      'length' => '0',
      'values' => 'teachCategory|teachName',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '25',
    1 => '26',
    2 => '28',
    3 => '29',
    4 => '30',
  ),
  'searchable' => 
  array (
  ),
);